version: '3.8'

services:
  flaskapp:
    build: .
    restart: always
    environment:
      # Configuraci√≥n de MySQL (VM1)
      - DB_HOST=bookstore-db.cb0m6ouewtu7.us-east-1.rds.amazonaws.com # IP PRIVADA real de VM1
      - DB_PORT=3306
      - DB_NAME=bookstore
      - DB_USER=admin
      - DB_PASSWORD=bookstore#1397Ltlt.
    ports:
      - "5000:5000"
    volumes:
      - /mnt/efs:/app/uploads 
