version: '3.8'

services:
  flaskapp:
    build: .
    restart: always
    environment:
      # Configuraci√≥n de MySQL (VM1)
      - DB_HOST=172.31.31.35  # IP PRIVADA real de VM1
      - DB_PORT=3306
      - DB_NAME=bookstore_db
      - DB_USER=bookstore_user
      - DB_PASSWORD=admin
    ports:
      - "5000:5000"
